/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package LDHGroup;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.geom.RoundRectangle2D;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.Timer;

/**
 *
 * @author Aby_daniel_
 */
public class SalesmanFormGUI extends javax.swing.JFrame {

    Timer t;
    SimpleDateFormat st;

    public SalesmanFormGUI() {
        setUndecorated(true);
        initComponents();
        setLocationRelativeTo(null);
        setSize(1080, 700);
        setShape(new RoundRectangle2D.Double(0, 0, getWidth(), getHeight(), 50, 50));
        dt();
        times();
    }

    public void dt() {
        Date d = new Date();
        SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
        String dd = sdf.format(d);
        livedate.setText(dd);
    }

    public void times() {

        t = new Timer(0, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Date dt = new Date();
                st = new SimpleDateFormat("hh:mm:ss a");
                String tt = st.format(dt);
                livetime.setText(tt);
            }
        });
        {
            t.start();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        enterPayroll = new javax.swing.JButton();
        managePayroll = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        livedate = new javax.swing.JLabel();
        livetime = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(1080, 750));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        enterPayroll.setBackground(new java.awt.Color(51, 255, 255));
        enterPayroll.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        enterPayroll.setText("Enter Payroll");
        enterPayroll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterPayrollActionPerformed(evt);
            }
        });
        jPanel1.add(enterPayroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 180, 170, 40));

        managePayroll.setBackground(new java.awt.Color(51, 255, 255));
        managePayroll.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        managePayroll.setText("Manage Payroll");
        managePayroll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                managePayrollActionPerformed(evt);
            }
        });
        jPanel1.add(managePayroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 240, 170, 40));

        exitButton.setBackground(new java.awt.Color(51, 255, 255));
        exitButton.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        exitButton.setText("Exit System");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });
        jPanel1.add(exitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 300, 170, 40));

        livedate.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        livedate.setText("0");
        jPanel1.add(livedate, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 150, 20));

        livetime.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        livetime.setText("0");
        jPanel1.add(livetime, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 140, 20));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LDHGroup/Maju Auto sales.png"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(1080, 750));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 1080, 690));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void enterPayrollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterPayrollActionPerformed
        PayrollForm frame2 = new PayrollForm();
        frame2.setVisible(true);
        dispose();
    }//GEN-LAST:event_enterPayrollActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitButtonActionPerformed

    private void managePayrollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managePayrollActionPerformed
        ManagePayroll frame3 = new ManagePayroll();
        frame3.setVisible(true);
        dispose();
    }//GEN-LAST:event_managePayrollActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SalesmanFormGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SalesmanFormGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SalesmanFormGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SalesmanFormGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SalesmanFormGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton enterPayroll;
    private javax.swing.JButton exitButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel livedate;
    private javax.swing.JLabel livetime;
    private javax.swing.JButton managePayroll;
    // End of variables declaration//GEN-END:variables
}
